### PR TITLE
Add borges indexer

### PR DESCRIPTION
**Pull request by erizocosmico**
(almost a million additions, you gotta love the `vendor` folder * sigh *)

### CODE REVIEW

**Comment by ajnavarro** [comment]
Can you split that PR in two commits please? one with `vendor` folder, and another with the code to review.

**Comment by erizocosmico** [comment]
Done, this is just the vendor folder

**Comment by vmarkovtsev** [comment]
CONTRIBUTING requires commit messages to start with a capital letter + the commit is no longer "add borges indexer".

Regarding `go vet`, I think the best workaround is to disable it on go 1.8.

**Comment by erizocosmico** [comment]
Just review second commit, first contains vendored code.

**Pull request merged**
